fields = ['id',
          'name',
          'screen_name',
          'is_admin',
          'admin_level',
          'is_member',
          'is_advertiser',
          'type',
          'photo_50',
          'photo_100',
          'photo_200']